package igu;

import javax.swing.JOptionPane;
import logica.InsertarDatosU;
import logica.Materias;

/**
 *
 * @author Alexander
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDatosU = new javax.swing.JPanel();
        jLabelDatosU = new javax.swing.JLabel();
        jLabelDato1 = new javax.swing.JLabel();
        jLabelDato2 = new javax.swing.JLabel();
        jLabelDato3 = new javax.swing.JLabel();
        jLabelDato4 = new javax.swing.JLabel();
        jTextFieldDato1 = new javax.swing.JTextField();
        jTextFieldDato2 = new javax.swing.JTextField();
        jTextFieldDato3 = new javax.swing.JTextField();
        jTextFieldDato4 = new javax.swing.JTextField();
        jPanelMaterias = new javax.swing.JPanel();
        jLabelMaterias = new javax.swing.JLabel();
        jLabelMat = new javax.swing.JLabel();
        jLabelCien = new javax.swing.JLabel();
        jLabelIng = new javax.swing.JLabel();
        jLabelArt = new javax.swing.JLabel();
        jPanelBimestres = new javax.swing.JPanel();
        jLabelBimestre = new javax.swing.JLabel();
        mat1 = new javax.swing.JTextField();
        cien1 = new javax.swing.JTextField();
        ing1 = new javax.swing.JTextField();
        art1 = new javax.swing.JTextField();
        mat2 = new javax.swing.JTextField();
        cien2 = new javax.swing.JTextField();
        ing2 = new javax.swing.JTextField();
        art2 = new javax.swing.JTextField();
        mat3 = new javax.swing.JTextField();
        cien3 = new javax.swing.JTextField();
        ing3 = new javax.swing.JTextField();
        art3 = new javax.swing.JTextField();
        mat4 = new javax.swing.JTextField();
        cien4 = new javax.swing.JTextField();
        ing4 = new javax.swing.JTextField();
        art4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnsubir = new javax.swing.JButton();
        btnprom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelDatosU.setBackground(new java.awt.Color(153, 153, 255));

        jLabelDatosU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelDatosU.setText("Datos De Usuario");

        jLabelDato1.setText("Carnet:");

        jLabelDato2.setText("Nombre:");

        jLabelDato3.setText("Apellido:");

        jLabelDato4.setText("Grado:");

        jTextFieldDato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDato1ActionPerformed(evt);
            }
        });

        jTextFieldDato2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDato2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosULayout = new javax.swing.GroupLayout(jPanelDatosU);
        jPanelDatosU.setLayout(jPanelDatosULayout);
        jPanelDatosULayout.setHorizontalGroup(
            jPanelDatosULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosULayout.createSequentialGroup()
                .addGroup(jPanelDatosULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosULayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabelDatosU))
                    .addGroup(jPanelDatosULayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelDatosULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelDatosULayout.createSequentialGroup()
                                .addGroup(jPanelDatosULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDato1)
                                    .addComponent(jLabelDato2))
                                .addGroup(jPanelDatosULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelDatosULayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldDato2, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE))
                                    .addGroup(jPanelDatosULayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldDato1))))
                            .addGroup(jPanelDatosULayout.createSequentialGroup()
                                .addGroup(jPanelDatosULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDato4)
                                    .addComponent(jLabelDato3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelDatosULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldDato4, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                                    .addComponent(jTextFieldDato3))))))
                .addContainerGap())
        );
        jPanelDatosULayout.setVerticalGroup(
            jPanelDatosULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosULayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelDatosU)
                .addGap(21, 21, 21)
                .addGroup(jPanelDatosULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDato1)
                    .addComponent(jTextFieldDato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDato2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDato3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDato3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDato4)
                    .addComponent(jTextFieldDato4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanelMaterias.setBackground(new java.awt.Color(153, 153, 255));

        jLabelMaterias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelMaterias.setText("Materias");

        jLabelMat.setText("Matematicas:");

        jLabelCien.setText("Ciencias:");

        jLabelIng.setText("Ingles:");

        jLabelArt.setText("Artes:");

        javax.swing.GroupLayout jPanelMateriasLayout = new javax.swing.GroupLayout(jPanelMaterias);
        jPanelMaterias.setLayout(jPanelMateriasLayout);
        jPanelMateriasLayout.setHorizontalGroup(
            jPanelMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMateriasLayout.createSequentialGroup()
                .addGroup(jPanelMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMateriasLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabelMaterias))
                    .addGroup(jPanelMateriasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelMat))
                    .addGroup(jPanelMateriasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelCien))
                    .addGroup(jPanelMateriasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelIng))
                    .addGroup(jPanelMateriasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelArt)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanelMateriasLayout.setVerticalGroup(
            jPanelMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMateriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMaterias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCien)
                .addGap(12, 12, 12)
                .addComponent(jLabelIng)
                .addGap(12, 12, 12)
                .addComponent(jLabelArt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBimestres.setBackground(new java.awt.Color(153, 153, 255));

        jLabelBimestre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelBimestre.setText("Bimestre1  Bimestre2  Bimestre3  Bimestre4");

        mat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat1ActionPerformed(evt);
            }
        });

        mat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat2ActionPerformed(evt);
            }
        });

        mat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat3ActionPerformed(evt);
            }
        });

        cien3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cien3ActionPerformed(evt);
            }
        });

        cien4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cien4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBimestresLayout = new javax.swing.GroupLayout(jPanelBimestres);
        jPanelBimestres.setLayout(jPanelBimestresLayout);
        jPanelBimestresLayout.setHorizontalGroup(
            jPanelBimestresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBimestresLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelBimestresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBimestresLayout.createSequentialGroup()
                        .addGroup(jPanelBimestresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(art1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(ing1)
                            .addComponent(cien1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mat1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(6, 6, 6)
                        .addGroup(jPanelBimestresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ing2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(cien2)
                            .addComponent(mat2)
                            .addComponent(art2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanelBimestresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelBimestresLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelBimestresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mat3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(cien3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelBimestresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mat4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(cien4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBimestresLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanelBimestresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelBimestresLayout.createSequentialGroup()
                                        .addComponent(art3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(art4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                    .addGroup(jPanelBimestresLayout.createSequentialGroup()
                                        .addComponent(ing3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ing4))))))
                    .addComponent(jLabelBimestre)))
        );
        jPanelBimestresLayout.setVerticalGroup(
            jPanelBimestresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBimestresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBimestre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBimestresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mat4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBimestresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cien2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cien3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cien4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBimestresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ing1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ing2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ing3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ing4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBimestresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(art1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(art2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(art3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(art4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        btnsubir.setBackground(new java.awt.Color(51, 51, 255));
        btnsubir.setForeground(new java.awt.Color(255, 255, 255));
        btnsubir.setText("Subir a db");
        btnsubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubirActionPerformed(evt);
            }
        });

        btnprom.setText("Promedio");
        btnprom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpromActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(btnsubir)
                .addGap(18, 18, 18)
                .addComponent(btnprom)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsubir)
                    .addComponent(btnprom))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDatosU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelBimestres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDatosU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBimestres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat2ActionPerformed

    private void mat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat3ActionPerformed

    private void cien3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cien3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cien3ActionPerformed

    private void jTextFieldDato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDato2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDato2ActionPerformed

    private void cien4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cien4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cien4ActionPerformed

    private void mat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mat1ActionPerformed

    private void btnsubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubirActionPerformed
        // Crear una instancia de InsertarDatosU pasando los JTextField
        InsertarDatosU insertarDatos = new InsertarDatosU(jTextFieldDato1, jTextFieldDato2, jTextFieldDato3, jTextFieldDato4);
        
        // Llamar al método para insertar los datos
        insertarDatos.MetodoInsertarDatosU();

    }//GEN-LAST:event_btnsubirActionPerformed

    private void btnpromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpromActionPerformed
try {
    // Obtener los valores de los JTextFields y convertir a double
    double nota1 = Double.parseDouble(mat1.getText());
    double nota2 = Double.parseDouble(mat2.getText());
    double nota3 = Double.parseDouble(mat3.getText());
    double nota4 = Double.parseDouble(mat4.getText());

    double nota5 = Double.parseDouble(cien1.getText());
    double nota6 = Double.parseDouble(cien2.getText());
    double nota7 = Double.parseDouble(cien3.getText());
    double nota8 = Double.parseDouble(cien4.getText());
    
    double nota9 = Double.parseDouble(ing1.getText());
    double nota10 = Double.parseDouble(ing2.getText());
    double nota11 = Double.parseDouble(ing3.getText());
    double nota12 = Double.parseDouble(ing4.getText());
    
    double nota13 = Double.parseDouble(art1.getText());
    double nota14 = Double.parseDouble(art2.getText());
    double nota15 = Double.parseDouble(art3.getText());
    double nota16 = Double.parseDouble(art4.getText());
    
    Materias materias = new Materias();

    double promedioMatematicas = materias.calcularPromedioMatematicas(nota1, nota2, nota3, nota4);
    double promedioCiencias = materias.calcularPromedioCiencias(nota5, nota6, nota7, nota8);
    double promedioIngles = materias.calcularPromedioIngles(nota9, nota10, nota11, nota12);
    double promedioArte = materias.calcularPromedioArte(nota13, nota14, nota15, nota16);
    
    JOptionPane.showMessageDialog(this, 
        "El promedio de Matematicas es: " + promedioMatematicas + 
        "\nEl promedio de Ciencias es: " + promedioCiencias +
        "\nEl promedio de Ingles es: " + promedioIngles +
        "\nEl promedio de Artes es: " + promedioArte);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Por favor, ingresa las notas en valores numericos");
}
    }//GEN-LAST:event_btnpromActionPerformed

    private void jTextFieldDato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDato1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDato1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField art1;
    private javax.swing.JTextField art2;
    private javax.swing.JTextField art3;
    private javax.swing.JTextField art4;
    private javax.swing.JButton btnprom;
    private javax.swing.JButton btnsubir;
    private javax.swing.JTextField cien1;
    private javax.swing.JTextField cien2;
    private javax.swing.JTextField cien3;
    private javax.swing.JTextField cien4;
    private javax.swing.JTextField ing1;
    private javax.swing.JTextField ing2;
    private javax.swing.JTextField ing3;
    private javax.swing.JTextField ing4;
    private javax.swing.JLabel jLabelArt;
    private javax.swing.JLabel jLabelBimestre;
    private javax.swing.JLabel jLabelCien;
    private javax.swing.JLabel jLabelDato1;
    private javax.swing.JLabel jLabelDato2;
    private javax.swing.JLabel jLabelDato3;
    private javax.swing.JLabel jLabelDato4;
    private javax.swing.JLabel jLabelDatosU;
    private javax.swing.JLabel jLabelIng;
    private javax.swing.JLabel jLabelMat;
    private javax.swing.JLabel jLabelMaterias;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBimestres;
    private javax.swing.JPanel jPanelDatosU;
    private javax.swing.JPanel jPanelMaterias;
    private javax.swing.JTextField jTextFieldDato1;
    private javax.swing.JTextField jTextFieldDato2;
    private javax.swing.JTextField jTextFieldDato3;
    private javax.swing.JTextField jTextFieldDato4;
    private javax.swing.JTextField mat1;
    private javax.swing.JTextField mat2;
    private javax.swing.JTextField mat3;
    private javax.swing.JTextField mat4;
    // End of variables declaration//GEN-END:variables
}
